# Generated by Django 5.1.2 on 2025-04-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='area_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='area_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='area_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='compactness_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='compactness_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='compactness_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concave_points_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concave_points_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concave_points_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concavity_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concavity_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='concavity_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fractal_dimension_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fractal_dimension_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fractal_dimension_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='perimeter_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='perimeter_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='perimeter_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='radius_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='radius_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='radius_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='smoothness_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='smoothness_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='smoothness_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='symmetry_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='symmetry_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='symmetry_worst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='texture_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='texture_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='texture_worst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
