# Generated by Django 5.1.2 on 2025-05-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0004_remove_patientdata_area_mean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='anxiety',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='coughing',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='fatigue',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='peer_pressure',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='shortness_of_breath',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='swallowing_difficulty',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='yellow_fingers',
        ),
    ]
