# Generated by Django 5.1.2 on 2025-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0005_remove_patientdata_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='coughing',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='shortness_of_breath',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='smoking',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='yellow_fingers',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
    ]
